
export const error_codes = {
  account_already_exist: "account_already_exist",
  Book_exist:"Book_exist",
  account_already_verified: "account_already_verified",
  account_not_verified: "account_not_verified",
  account_not_found: "account_not_found",
  actor_suspended: "actor_suspended",
  already_member: "already_member",
  bank_acc_error_not_provided: "bank_acc_error_not_provided",
  bvn_account_mismatched: "bvn_account_mismatched",
  bvn_error_not_provided: "bvn_error_not_provided",
  can_only_revoke: "can_only_revoke",
  category_exist: "category_exist",
  category_not_found: "category_not_found",
  file_too_large: "file_too_large",
  incorrect_otp: "incorrect_otp",
  incorrect_email_or_password: "incorrect_email_or_password",
  invalid_acc_number: "invalid_acc_number",
  invalid_alternative_email: "invalid_alternative_email",
  invalid_alternative_phone: "invalid_alternative_phone",
  invalid_bank_name: "invalid_bank_name",
  invalid_birth_date: "invalid_birth_date",
  invalid_bvn: "invalid_bvn",
  invalid_email: "invalid_email",
  invalid_name: "invalid_name",
  invalid_phone: "invalid_phone",
  invalid_password:"invalid_password",
  invalid_key:"invalid_key",
  invalid_code: "invalid_code",
  invalid_input: "invalid_input",
  members_exist: "members_exist",
  membership_disapproved: "membership_disapproved",
  membership_revoked: "membership_revoked",
  mismatched_category: "mismatched_category",
  no_disapproval_message: "no_disapproval_message",
  not_orgnization_member: "not_orgnization_member",
  org_not_found: "org_not_found",
  otp_expired: "otp_expired",
  password_too_short: "password_too_short",
  sub_category_exist: "sub_category_exist",
  sub_category_not_found: "sub_category_not_found",
  unauthorized: "unauthorized",
  user_already_exist: "user_already_exist",
  user_not_found: "user_not_found",
  user_datail_not_found: "user_datail_not_found",
  weak_password: "weak_password",
  account_suspended:"account_suspended",
  permission_error:"permission_error",
  staff_not_initiated:"staff_not_initiated",
}
